favicon: null
name: Reel Stories Digital Media
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.1183673604391515
  brandStrength: 0.7025972558185458
  lightness: 0.7631758502684534
  brandColors:
    - '#09070A'
    - '#BCBCBE'
    - '#EDECED'
    - '#71604C'
    - '#CC8359'
  rhythmicContrast: 0.2845245799981058
typography_spectrum: 0.1616541
layout_spectrum: 0.8952738
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
