name: Reel Stories Digital Media
favicon: null
layout_spectrum: 0.41137880156747997
typography_spectrum: 0.17624707473441958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7025972558185458
  lightness: 0.7631758502684534
  saturation: 0.11836736043915153
  rhythmicContrast: 0.28452457999810576
purpose: []
